# MADE BY:
#  __    __                                          __        __  __  __                     
# /  |  /  |                                        /  |      /  |/  |/  |                    
# $$ |  $$ |  ______   _______    ______    ______  $$ |____  $$/ $$ |$$/   _______  __    __ 
# $$  \/$$/  /      \ /       \  /      \  /      \ $$      \ /  |$$ |/  | /       |/  |  /  |
#  $$  $$<  /$$$$$$  |$$$$$$$  |/$$$$$$  |/$$$$$$  |$$$$$$$  |$$ |$$ |$$ |/$$$$$$$/ $$ |  $$ |
#   $$$$  \ $$    $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |$$ |$$ |$$ |      $$ |  $$ |
#  $$ /$$  |$$$$$$$$/ $$ |  $$ |$$ \__$$ |$$ |__$$ |$$ |  $$ |$$ |$$ |$$ |$$ \_____ $$ \__$$ |
# $$ |  $$ |$$       |$$ |  $$ |$$    $$/ $$    $$/ $$ |  $$ |$$ |$$ |$$ |$$       |$$    $$ |
# $$/   $$/  $$$$$$$/ $$/   $$/  $$$$$$/  $$$$$$$/  $$/   $$/ $$/ $$/ $$/  $$$$$$$/  $$$$$$$ |
#                                         $$ |                                      /  \__$$ |
#                                         $$ |                                      $$    $$/ 
#                                         $$/                                        $$$$$$/       
VERSION: "1.0.3" # Internal use only

# Choose your transfer type:
# "External" will use `transferserver` to move players between SERVERS
# "Internal" will use your preset command string to move players between WORLDS
Transfer-Type: "External"

# This is the command string that will be used to transfer players between WORLDS
# Don't worry about this if you're using the External transfer type
# Use '{player}' for the player's name
# Use '{world}' for the world name
World-CMD: "multiworld tp {world} {player}"

# This is where you choose if world command should be run by the player or the console
# Options are: "Console" and "Player"
World-CMD-Mode: "Console"

# Choose whether the selector item should be enabled
Selector-Support: true

# Choose what item the server selector should be
Selector-Item: 345

# Choose what slot the selector should appear in
# The range for this input is 0-35
Selector-Slot: 0

# This is the text that will show on the selector in the player's inventory!
Selector-Name: "§r§aServer Selector §7[Open]"

# This is the title of the transfer UI
# Don't worry about this if you're using the Internal transfer type
UI-Title: "§l§2Server Selector"

# This is the message the will show under your title on the transfer UI
# Don't worry about this if you're using the Internal transfer type
UI-Message: "§r§7Click the server you want to join"

# This is where you list your servers or worlds to be displayed on the transfer UI
# You can use '§' and '&' on the labels to style your servers or worlds inside the UI
# For images, use 'url' or 'path' to show an image in the menus (or leave blank to disable)
# Note: If you are using a URL, do NOT include the 'https://' or 'http://' in the link!
# If you are using the Internal transfer type, the world name will be taken from the 'WorldName' key

# Add as many servers or worlds as you'd like:
# Add servers using this format → ServerTitle:ServerIP:ServerPort:ImageType:Path/URL
# Add worlds using this format → WorldTitle:WorldAlias:ImageType:Path/URL
List:
  - "§7KitPvP:104.238.220.207:25579" # ← External server example
#  - "&l&5Creative:creative:url:i.imgur.com/8pbNECc.png" ← Internal world example
